# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 9000

spring:
# THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    enabled: true
    cache: false
# INTERNATIONALIZATION (MessageSourceAutoConfiguration)
  messages:
    basename: messages
    cache-seconds: -1
    encoding: UTF-8
#Database Configuration
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url:             jdbc:mysql://localhost:3306/jeefw?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=UTF-8
    username: jeefw
    password: jeefw
    initialize: false
    continueOnError: true
# JOOQ
jooq:
  sql:
    dialect: MySQL

